config:
  target: 'http://localhost:8080' # 요청을 보낼 대상
  phases:
    - duration: 30  # 30초 동안
      arrivalRate: 3  # 초당 3개의 요청을 보낸다
      name: Warm up
    - duration: 30
      arrivalRate: 3
      rampTo: 30  # 점점 Throughput을 늘린다(부하를 점점 늘린다)
      name: Ramp up load
    - duration: 60
      arrivalRate: 30
      name: Sustained load
    - duration: 30
      arrivalRate: 30
      rampTo: 10
      name: End of load
scenarios: # 한 명의 사용자가 어떤 순서대로 요청을 해나갈 것인지 작성
  - name: "search stores by category"
    flow:
      - get:
          url: "/categories/1"
